# Generated by Django 5.0.1 on 2024-03-24 16:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("general", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=2,
                                message="Длина поля от 5 до 100 символов.",
                            ),
                            django.core.validators.RegexValidator(
                                message="Направление разработки может содержать: кириллические и латинские символы.",
                                regex="(^[A-Za-zА-Яа-яЁё]+)\\Z",
                            ),
                        ],
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление разработки",
                "verbose_name_plural": "Направления разработки",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.TextField(
                        blank=True,
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Телефон может содержать: цифры, спецсимволы, длина не должна превышать 12 символов",
                                regex="^\\+7\\(\\d{3}\\)\\d{3}-\\d{2}-\\d{2}$",
                            )
                        ],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "telegram_nick",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=5,
                                message="Длина поля от 5 до 32 символов.",
                            ),
                            django.core.validators.RegexValidator(
                                message="Введите корректное имя пользователя. Оно может состоять из латинских букв, цифр и символа подчеркивания.",
                                regex="^[a-zA-Z0-9_]+$",
                            ),
                        ],
                        verbose_name="Ник в телеграм",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=256, verbose_name="E-mail"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=5,
                                message="Длина поля от 5 до 100 символов.",
                            ),
                            django.core.validators.RegexValidator(
                                message="Название проекта может содержать: кириллические и латинские символы, цифры и символы .,-—+/:",
                                regex="(^[+/:,.0-9A-Za-zА-Яа-яЁё\\-–—]+)\\Z",
                            ),
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=750,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=50,
                                message="Длина поля от 50 до 750 символов.",
                            )
                        ],
                        verbose_name="Описание",
                    ),
                ),
                (
                    "started",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "ended",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "busyness",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, 10), (2, 20), (3, 30), (4, 40)],
                        null=True,
                        verbose_name="Занятость (час/нед)",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Активен"),
                            (2, "Завершен"),
                            (3, "Черновик"),
                        ],
                        verbose_name="Статус",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        max_length=256,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=5,
                                message="Длина поля от 5 до 256 символов.",
                            )
                        ],
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Организатор",
                    ),
                ),
                (
                    "directions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects_direction",
                        to="projects.direction",
                        verbose_name="Направления разработки",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects_participated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участники",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="ProjectSpecialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveSmallIntegerField(
                        verbose_name="Количество"
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "intern"),
                            (2, "junior"),
                            (3, "middle"),
                            (4, "senior"),
                            (5, "lead"),
                        ],
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, verbose_name="Требуется"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        to="general.skill", verbose_name="Навыки"
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="general.specialist",
                        verbose_name="Специалист",
                    ),
                ),
            ],
            options={
                "verbose_name": "Специалист проекта",
                "verbose_name_plural": "Специалисты проекта",
                "default_related_name": "project_specialists",
            },
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("creator", "name"),
                name="projects_project_unique_name_per_creator",
            ),
        ),
    ]
