# Generated by Django 5.0.1 on 2024-03-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="busyness",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, 10), (2, 20), (3, 30), (4, 40)],
                null=True,
                verbose_name="Занятость (час/нед)",
            ),
        ),
    ]
