# Generated by Django 5.0.1 on 2025-09-18 07:26

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0021_alter_invitationtoproject_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=1500,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=20,
                        message="Длина поля от 20 до 1500 символов.",
                    ),
                    django.core.validators.RegexValidator(
                        flags=re.RegexFlag["IGNORECASE"],
                        message="Описание может содержать: кириллические и латинские буквы, цифры и специальные символы.",
                        regex="(^[\\Wa-zа-яё0-9\\s]+)\\Z",
                    ),
                ],
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="directions",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="projects_direction",
                to="projects.direction",
                verbose_name="Направления разработки",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="ended",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата завершения"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="started",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата начала"
            ),
        ),
    ]
