# Generated by Django 5.0.1 on 2024-03-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_organizer",
            field=models.BooleanField(
                default=False, verbose_name="Организатор проекта"
            ),
        ),
    ]
