[tool.poetry]
name = "my-project"
version = "0.1.0"
description = ""
authors = ["CodePET"]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
