services:

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_value:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  backend:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_NAME}_backend:latest
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/backend_static
      - ./.env:/app
    depends_on:
      - db

  nginx:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_NAME}_nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/static
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend

volumes:
  db_value:
  static_volume:
