services:

  db:
    image: postgres:16.2-alpine
    restart: always
    env_file: .env
    volumes:
      - db_value:/var/lib/postgresql/data/


  backend:
    build: ../.
    env_file: .env
    volumes:
      - static_volume:/backend_static/
      - ./.env:/app
    depends_on:
      - db

  nginx:
    build: ./nginx/.
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/staticfiles/
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend

volumes:
  db_value:
  static_volume:
