name: code-pet

services:
  db:
    image: postgres:16.2-alpine
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_value:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 5

  backend:
    build: ../.
    env_file: .env
    volumes:
      - static_volume:/backend_static/
      - ./.env:/app
    command:
      - /bin/sh
      - -c
      - |
        python manage.py collectstatic -c --noinput
        cp -r /backend/static/. /backend_static/static
        python manage.py makemigrations
        python manage.py migrate
        gunicorn --bind 0.0.0.0:8000 config.wsgi
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine3.18
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  celery:
    build: ../.
    env_file: .env
    command: celery -A config.celery worker -l info -E
    volumes:
      - ./.env:/app
    depends_on:
      - backend

  celery-beat:
    build: ../.
    env_file: .env
    command: celery -A config beat -l info
    volumes:
      - ./.env:/app
    depends_on:
      - backend

  nginx:
    image: nginx:1.25.2-alpine3.18-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/staticfiles/
    depends_on:
      - backend

volumes:
  db_value:
  static_volume:
