BOOL_CHOICES = [(True, "Готов"), (False, "Не готов")]
MAX_LENGTH_NAME = 30
MAX_LENGTH_COUNTRY = 255
MAX_LENGTH_CITY = 255
MAX_LENGTH_ABOUT = 750
MAX_LENGTH_URL = 256
MIN_LENGTH_NAME = 2
MIN_LENGTH_ABOUT = 50
MIN_LENGTH_PORTFOLIO = 5
VISIBLE_CHOICES = [
    (1, "All"),
    (2, "Only creator"),
    (3, "Nobody"),
]
