# Generated by Django 5.0.1 on 2024-02-29 23:57

import apps.profile.validators
import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0002_section_page_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.skill')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.specialization')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='images/', validators=[apps.profile.validators.validate_image], verbose_name='Аватар')),
                ('nickname', models.CharField(max_length=30, unique=True, validators=[apps.profile.validators.validate_nickname], verbose_name='Никнейм')),
                ('name', models.CharField(max_length=30, validators=[apps.profile.validators.validate_nickname], verbose_name='Имя')),
                ('about', models.TextField(validators=[apps.profile.validators.validate_about], verbose_name='О себе')),
                ('portfolio_link', models.URLField()),
                ('contacts', models.TextField(validators=[apps.profile.validators.validate_phone_number])),
                ('birthday', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1950, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 3, 1))], verbose_name='Дата рождения')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('level', models.CharField(choices=[(1, 'junior'), (2, 'middle'), (3, 'senior'), (4, 'lead')], max_length=255, verbose_name='Уровень квалификации')),
                ('ready_to_participate', models.BooleanField(choices=[(True, 'Готов'), (False, 'Не готов')], verbose_name='Готовность к участию в проектах')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.userskill', verbose_name='Навыки')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.userspecialization', verbose_name='Специальность')),
            ],
        ),
    ]
