# Generated by Django 5.0.1 on 2025-07-27 15:59

import apps.general.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0011_alter_profile_about_alter_profile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.TextField(
                blank=True,
                max_length=1500,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите кириллицу или латиницу",
                        regex="^[\\wа-яА-ЯёЁ0-9\\s<>,.?!'\\\"/\\-+:;@#\\$%\\^&\\*\\(\\)\\[\\]\\{\\}]*$|^<.*>$",
                    )
                ],
                verbose_name="О себе",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите кириллицу или латиницу",
                        regex="^[a-zA-Zа-яА-ЯёЁ-]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=2, message="Должно быть минимум символов"
                    ),
                ],
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="portfolio_link",
            field=apps.general.fields.CustomURLField(
                blank=True,
                max_length=256,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=5,
                        message="Длинна URL-адреса должна быть от 5 до 256 символов.",
                    )
                ],
                verbose_name="Ссылка на портфолио",
            ),
        ),
    ]
