# Generated by Django 5.0.1 on 2024-02-20 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("general", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название проекта"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=3000, verbose_name="Описание проекта"
                    ),
                ),
                (
                    "started",
                    models.DateField(
                        blank=True, null=True, verbose_name="Начало проекта"
                    ),
                ),
                (
                    "ended",
                    models.DateField(
                        blank=True, null=True, verbose_name="Окончание проекта"
                    ),
                ),
                (
                    "busyness",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "10"), (2, "20"), (3, "30"), (4, "40")],
                        verbose_name="Занятость в часах в неделю",
                    ),
                ),
                (
                    "recruitment_status",
                    models.BooleanField(
                        default=False, verbose_name="Статус набора участников"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Активен"), (2, "Завершен")],
                        verbose_name="Статус проекта",
                    ),
                ),
                (
                    "contacts",
                    models.TextField(
                        max_length=256, verbose_name="Контакты для связи"
                    ),
                ),
                (
                    "direction",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Десктоп"), (2, "Веб"), (3, "Мобильная")],
                        verbose_name="Направление разработки",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Организатор",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects_participated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участники проекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название специализации"
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialists",
                        to="general.specialization",
                        verbose_name="Специальность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Специалист",
                "verbose_name_plural": "Специалисты",
            },
        ),
        migrations.CreateModel(
            name="ProjectSpecialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveSmallIntegerField(
                        verbose_name="Количество"
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "intern"),
                            (2, "junior"),
                            (3, "middle"),
                            (4, "senior"),
                            (5, "lead"),
                        ],
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, verbose_name="Требуется для проекта"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        to="general.skill", verbose_name="Навыки"
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.specialist",
                        verbose_name="Специалист",
                    ),
                ),
            ],
            options={
                "verbose_name": "Специалист проекта",
                "verbose_name_plural": "Специалисты проекта",
                "default_related_name": "project_specialists",
            },
        ),
    ]
