# Generated by Django 5.0.1 on 2024-02-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_project_recruitment_status_alter_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="busyness",
            field=models.IntegerField(
                verbose_name="Занятость в часах в неделю"
            ),
        ),
    ]
