# Generated by Django 5.0.1 on 2024-02-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_alter_specialization_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialist",
            options={
                "verbose_name": "Специальность",
                "verbose_name_plural": "Специальности",
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="level",
        ),
        migrations.AlterField(
            model_name="project",
            name="skills",
            field=models.ManyToManyField(
                related_name="project_skills",
                to="project.skill",
                verbose_name="Навыки",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="specialists",
            field=models.ManyToManyField(
                related_name="projects",
                to="project.specialist",
                verbose_name="Специальности",
            ),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Название cпециальности"
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Название специализации"
            ),
        ),
        migrations.CreateModel(
            name="ProjectSpecialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialists_count",
                    models.IntegerField(
                        verbose_name="Количество требуемых специалистов"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, verbose_name="Требуется для проекта"
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.level",
                        verbose_name="Уровень специалиста",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_specialists",
                        to="project.project",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_specialists",
                        to="project.specialist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Специалист проекта",
                "verbose_name_plural": "Специалисты проекта",
            },
        ),
    ]
