# Generated by Django 5.0.1 on 2024-02-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialist",
            options={
                "verbose_name": "Специалист",
                "verbose_name_plural": "Специалисты",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="busyness",
            field=models.IntegerField(
                choices=[(1, "Полная занятость"), (2, "Частичная занятость")],
                verbose_name="Занятость",
            ),
        ),
    ]
