# Generated by Django 5.0.1 on 2024-02-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_alter_specialist_options_alter_project_busyness"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="recruitment_status",
            field=models.IntegerField(
                choices=[(1, "Набор открыт"), (2, "Набор закрыт")],
                default=1,
                verbose_name="Статус набора участников",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.status",
                verbose_name="Статус проекта",
            ),
        ),
    ]
