# Generated by Django 5.0.1 on 2024-03-24 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(max_length=100, verbose_name="Заголовок"),
                ),
                (
                    "description",
                    models.TextField(max_length=250, verbose_name="Текст"),
                ),
                (
                    "page_id",
                    models.PositiveSmallIntegerField(
                        verbose_name="Идентификатор страницы"
                    ),
                ),
            ],
            options={
                "verbose_name": "Секция",
                "verbose_name_plural": "Секции",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
            },
        ),
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=2,
                                message="Длина поля от 2 до 50 символов.",
                            ),
                            django.core.validators.RegexValidator(
                                message="Специальность может содержать: кириллические и латинские символы.",
                                regex="(^[A-Za-zА-Яа-яЁё]+)\\Z",
                            ),
                        ],
                        verbose_name="Специализация",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=2,
                                message="Длина поля от 2 до 2 символов.",
                            ),
                            django.core.validators.RegexValidator(
                                message="Специализация может содержать: кириллические и латинские символы,пробелы и символ /",
                                regex="(^[A-Za-zА-Яа-яЁё\\s\\/]+)\\Z",
                            ),
                        ],
                        verbose_name="Специальность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Специалист",
                "verbose_name_plural": "Специалисты",
            },
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("title", "page_id"),
                name="general_section_unique_section_per_page",
            ),
        ),
        migrations.AddConstraint(
            model_name="specialist",
            constraint=models.UniqueConstraint(
                fields=("specialty", "specialization"),
                name="general_specialist_unique_specialist",
            ),
        ),
    ]
