# Generated by Django 5.0.1 on 2024-03-20 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialist",
            name="specialization",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=2, message="Длина поля от 2 до 100 символов."
                    ),
                    django.core.validators.RegexValidator(
                        message="Специализация может содержать: кириллические и латинские символы,пробелы и символ /",
                        regex="(^[A-Za-zА-Яа-яЁё\\s\\/]+)\\Z",
                    ),
                ],
                verbose_name="Специальность",
            ),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="specialty",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=2,
                        message="Длина поля от 2 до 50 символов.",
                    ),
                    django.core.validators.RegexValidator(
                        message="Специальность может содержать: кириллические и латинские символы.",
                        regex="(^[A-Za-zА-Яа-яЁё]+)\\Z",
                    ),
                ],
                verbose_name="Специализация",
            ),
        ),
    ]
