# Generated by Django 5.0.1 on 2024-02-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="description",
            field=models.TextField(max_length=250, verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="section",
            name="title",
            field=models.TextField(max_length=100, verbose_name="Заголовок"),
        ),
    ]
