# Generated by Django 5.0.1 on 2024-02-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="page_id",
            field=models.IntegerField(
                default=0, verbose_name="Идентификатор страницы"
            ),
        ),
    ]
